[package]
name = "tetris-ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.4.0"
dioxus-desktop = "0.4.0"
num_enum = "0.7.0"
rand = "0.8.5"
tokio = "1.33.0"
